// <auto-generated />
namespace App.Database.LogsMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTraces : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTraces));
        
        string IMigrationMetadata.Id
        {
            get { return "201801151636468_AddTraces"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
